// This file should be generated by running:
// npx supabase gen types typescript --project-id YOUR_PROJECT_ID --schema public > lib/database.types.ts
// For now, a placeholder:
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      projects: {
        Row: {
          id: string
          user_id: string
          title: string
          description: string | null
          grid_config: Json // You might want to type this more strictly as GridConfig
          created_at: string
          updated_at: string
          is_public: boolean
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          description?: string | null
          grid_config: Json
          created_at?: string
          updated_at?: string
          is_public?: boolean
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          description?: string | null
          grid_config?: Json
          created_at?: string
          updated_at?: string
          is_public?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "projects_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      project_images: {
        Row: {
          id: string
          project_id: string
          storage_path: string
          original_filename: string
          file_size: number | null
          mime_type: string | null
          content: string | null
          color: string | null
          uploaded_at: string
          position: number | null
          row_span: number | null
          col_span: number | null
          placed_at: string | null
        }
        Insert: {
          id?: string
          project_id: string
          storage_path: string
          original_filename: string
          file_size?: number | null
          mime_type?: string | null
          content?: string | null
          color?: string | null
          uploaded_at?: string
          position?: number | null
          row_span?: number | null
          col_span?: number | null
          placed_at?: string | null
        }
        Update: {
          id?: string
          project_id?: string
          storage_path?: string
          original_filename?: string
          file_size?: number | null
          mime_type?: string | null
          content?: string | null
          color?: string | null
          uploaded_at?: string
          position?: number | null
          row_span?: number | null
          col_span?: number | null
          placed_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "project_images_project_id_fkey"
            columns: ["project_id"]
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}
